[package]
name = "number-stream-accumulation"
version = "0.1.0"
authors = ["Shale Xiong <shale.xiong@arm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2"
serde = "1.0"
libveracruz = {path = "../../libveracruz"}

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
