[package]
name = "pinecone-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2.5"
serde = { version = "1.0.3", features = ["derive"] }
rand = "0.8"
