[package]
name = "generate-policy"
version = "0.1.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Generates Veracruz policy files from a set of command line parameters."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
data-encoding = "2.3.2"
env_logger = "0.8.2"
log = "0.4.14"
ring = "0.17.0-alpha.8"
serde_json = "1.0.62"