cargo-features = ["resolver"]

[package]
authors = ["The Veracruz Development Team"]
description = "Workspace for trusted Linux services"
edition = "2018"
name = "linux-runtime"
version = "0.3.0"

[workspace]
members = [
  "crates/linux-root-enclave",
  "crates/runtime-manager",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[patch.crates-io]
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed" }
serde = { git = "https://github.com/veracruz-project/serde.git", branch = "veracruz" }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
