[package]
name = "postcard-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
postcard = { version = "0.7.2", features = [ "alloc" ] }
serde = { version = "1.0.3", features = ["derive"] }
rand = "0.8"
