[package]
authors = ["The Veracruz Development Team"]
description = "TLS endpoint and session management for the trusted Veracruz runtime"
edition = "2018"
name = "session-manager"
version = "0.3.0"

[features]
sgx = [
  "policy-utils/sgx",
  "sgx_tstd",
  "sgx_types",
  "rustls/mesalock_sgx",
  "webpki/mesalock_sgx",
  "ring/mesalock_sgx",
]
# NOTE: turn on the `std` on ring for Error trait
icecap = [
  "ring/std",
  "ring/non_sgx",
  "policy-utils/icecap"
]
nitro = [
  "ring/std",
  "ring/non_sgx",
  "policy-utils/std"
]
std = [
  "ring/std",
  "policy-utils/std"
]
tz = [
  "policy-utils/tz",
  "webpki/default",
  "ring/std",
  "ring/non_sgx",
  "optee-utee",
  "rustls/default",
]

[dependencies]
err-derive = "0.2"
optee-utee = { git = "https://github.com/veracruz-project/rust-optee-trustzone-sdk.git", branch = "veracruz-v1", optional = true }
policy-utils = { path = "../policy-utils" }
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz-v1" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz-v1" }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz-v1" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', branch = "veracruz-v1", optional = true }
