cargo-features = ["resolver"]

[workspace]
members = [
  "crates/runtime-manager",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[patch.crates-io]
libc = { git = "https://github.com/veracruz-project/libc.git", branch = "veracruz" }
ring = { git = "https://github.com/mathias-arm/ring.git", branch = "icecap" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed" }
webpki = { git = "https://github.com/mathias-arm/webpki.git", branch = "unrecognized_extensions" }
