[package]
authors = ["The Veracruz Development Team"]
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"
edition = "2018"
name = "veracruz-utils"
version = "0.3.0"

[features]

icecap = ["serde/derive", "ring"]
linux = ["serde_json/std", "ring/non_sgx", "serde/derive"]
nitro = ["serde/derive", "serde_json/std", "ring/non_sgx"]
sgx = ["sgx_tstd", "serde/mesalock_sgx", "serde_json/mesalock_sgx", "serde_json/alloc", "ring/mesalock_sgx"]
std = ["serde/std", "rustls", "serde_json/std", "ring"]
tz = ["serde_json/std", "ring"]

[dependencies]
err-derive = "0.2"
ring = { git = "https://github.com/veracruz-project/ring.git", version = "=0.16.11", branch = "veracruz", optional = true }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz", optional = true }
serde = { git = "https://github.com/veracruz-project/serde.git", default-features = false, branch = "veracruz", optional = true }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", default-features = false }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[build-dependencies]
uuid = { version = "0.7", features = ["v4"] }

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { branch = "veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
