[package]
authors = ["The Veracruz Development Team"]
description = "Veracruz integration test-suite.  Tests trusted Veracruz runtime functioanlity, and session management code, without establishing a network connection."
edition = "2018"
name = "veracruz-server-test"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
icecap = [
  "veracruz-server/icecap",
  "proxy-attestation-server/icecap",
  "policy-utils/icecap",
  "veracruz-utils/icecap",
]
linux = [
  "veracruz-server/linux",
  "policy-utils/std",
  "veracruz-utils/linux",
  "proxy-attestation-server/linux",
]
nitro = ["veracruz-server/nitro", "proxy-attestation-server/nitro", "policy-utils/std", "veracruz-utils/nitro"]
sgx = [
  "sgx_ucrypto",
  "sgx_urts",
  "sgx_types",
  "veracruz-server/sgx",
  "proxy-attestation-server/sgx",
  "transport-protocol/sgx_attestation",
  "policy-utils/std",
  "veracruz-utils/std",
]
tz = [
  "veracruz-server/tz",
  "proxy-attestation-server/tz",
  "transport-protocol/tz",
  "policy-utils/std",
  "veracruz-utils/std",
]
# debug feature means the enclaves will be started in debug mode (when available)
# which changes behaviors depending on the platform (for example in Debug mode,
# Nitro enclave attestation documents have the PCRs zeroed out and the console
# cannot connect)
debug = ["veracruz-server/debug"]

[dependencies]
actix-rt = "1.1.1"
curl = "=0.4.35"
env_logger = "0.7"
hex = "=0.4.2"
http = "=0.2.4"
lazy_static = "1.4"
log = "=0.4.13"
policy-utils = { path = "../policy-utils", optional = true }
proxy-attestation-server = { path = "../proxy-attestation-server" }
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz-v1" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz-v1" }
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
transport-protocol = { path = "../transport-protocol" }
veracruz-server = { path = "../veracruz-server" }
veracruz-utils = { path = "../veracruz-utils", optional = true }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz-v1" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', branch = "veracruz-v1", optional = true }
sgx_types = { git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', branch = "veracruz-v1", optional = true }
sgx_ucrypto = { git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', branch = "veracruz-v1", optional = true }

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz-v1" }
