[package]
name = "freestanding-chihuahua"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A freestanding WASM execution engine implementing the Veracruz ABI for offline development and testing."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chihuahua = { path = "../../chihuahua", features = ["std"] }
clap = "2.33.3"
env_logger = "0.7.1"
log = "0.4.8"
serde = { version = "1.0.103", features = ["derive"] }
toml = "0.5.5"
wasmi = { git = "https://github.com/veracruz-project/wasmi.git", branch="veracruz", features = ["non_sgx"] }

[[bin]]
name = "freestanding-chihuahua"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
