blank_lines_upper_bound=1
brace_style="SameLineWhere"
combine_control_expr=false
condense_wildcard_suffixes=true
control_brace_style="AlwaysSameLine"
enum_discrim_align_threshold=20
fn_args_layout="Compressed"
force_multiline_blocks=true
format_code_in_doc_comments=true
format_macro_matchers=true
format_macro_bodies=true
format_strings=true
imports_indent="Block"
imports_layout="HorizontalVertical"
indent_style="Block"
inline_attribute_width=0
match_arm_blocks=false
merge_derives=true
merge_imports=true
max_width=100
comment_width=75
normalize_comments=true
normalize_doc_attributes=true
reorder_impl_items=true
report_fixme="Always"
report_todo="Always"
tab_spaces=4
