[package]
name = "io-utils"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Common IO-related code used by multiple Veracruz components."

[features]
nitro = ["serde_json/std", "nix", "byteorder"]

[dependencies]
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde = { git = "https://github.com/veracruz-project/serde.git", features=["derive"], branch = "veracruz" }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", default-features = false }
err-derive = "0.2"
nix = { version = "0.15", optional = true }
byteorder = { version = "1.3", optional = true }
