[package]
name = "policy-utils"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Miscellaneous code related to the Veracruz policy."

[features]
sgx    = ["sgx_tstd", "serde/mesalock_sgx", "serde_json/mesalock_sgx", "serde_json/alloc", "ring/mesalock_sgx", "wasi-types/sgx"]
std    = ["serde/std", "serde_json/std", "ring", "x509-parser", "rustls", "wasi-types/std"]
icecap = ["ring"]
tz     = ["serde_json/std", "ring", "wasi-types/std"]

[dependencies]
x509-parser = { version = "0.7.0", optional = true }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde = { git = "https://github.com/veracruz-project/serde.git", features=["derive"], branch = "veracruz" }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", default-features = false }
err-derive = {version = "0.2", default-features = false }
ring = { git = "https://github.com/veracruz-project/ring.git", version = "=0.16.11", branch = "veracruz", optional = true }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz", optional = true }
hex = { version = "=0.4.2", default-features = false }
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }

# Pinned due to Rust compiler version.
lexical-core = { version = "=0.7.0", default-features = false }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
