[package]
authors = ["The Veracruz Development Team"]
build = "build.rs"
description = "Veracruz protocol message wire-format parsing and serialization code for the trusted Veracruz runtime"
edition = "2018"
name = "transport-protocol"
version = "0.3.0"

[features]
icecap = []
sgx = ["protobuf/mesalock_sgx", "sgx_types", "sgx_tstd"]
sgx_attestation = ["sgx_types"]
tz = []

[dependencies]
err-derive = "0.2"
protobuf = { git = "https://github.com/veracruz-project/rust-protobuf.git", branch = "veracruz-v1" }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[build-dependencies]
protoc-rust = { git = "https://github.com/veracruz-project/rust-protobuf.git", branch = "veracruz-v1" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', branch = "veracruz-v1", optional = true }
