cargo-features = ["resolver"]

[package]
authors = ["The Veracruz Development Team"]
description = "Workspace for untrusted IceCap services and tests"
edition = "2018"
name = "icecap-host"
version = "0.3.0"

[workspace]
members = [
  "crates/proxy-attestation-server",
  "crates/veracruz-client",
  "crates/veracruz-server",
  "crates/veracruz-server-test",
  "crates/veracruz-test",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed" }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
