[package]
name = "image-processing"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Image processing example. Read an image from the virtual filesystem, apply a transform to it (crop) and save it"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }

[profile.release]
codegen-units = 1
opt-level = 3

