[package]
name = "audio-event-triangulation"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Triangulation via audio events"

[dependencies]
anyhow = "1.0.14"
thiserror = "1.0.26"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

